// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRrRS9SegKYRAFhTn_dya96QvV6ZZfinQ',
    appId: '1:693069361385:android:013481698855c786698078',
    messagingSenderId: '693069361385',
    projectId: 'food-delivery-express-7f7fc',
    storageBucket: 'food-delivery-express-7f7fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbg8RcImbiRDtkGNhQnBamo4tuBJYjSA',
    appId: '1:693069361385:ios:4abe39dc40e5156b698078',
    messagingSenderId: '693069361385',
    projectId: 'food-delivery-express-7f7fc',
    storageBucket: 'food-delivery-express-7f7fc.appspot.com',
    androidClientId: '693069361385-jsnc4hs9i35rgah68hejrvs2s5c1h801.apps.googleusercontent.com',
    iosClientId: '693069361385-ijoqj73s3qta7e96k1f5k0d6q9ms3eog.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiLanguges',
  );
}
